# Generated by Django 6.0.6 on 2026-08-26 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_remove_productsize_product_color_size_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='color',
            name='color',
            field=models.CharField(choices=[('White', 'White'), ('Black', 'Black'), ('Blue', 'Blue')], max_length=50),
        ),
    ]
