# Generated by Django 6.0.6 on 2026-09-07 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_order_apartment_order_company_name_order_coupon_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='color',
            name='color',
            field=models.CharField(blank=True, choices=[('Red', 'Red'), ('Blue', 'Blue'), ('Green', 'Green'), ('Black', 'Black'), ('White', 'White'), ('Yellow', 'Yellow')], max_length=50, null=True),
        ),
    ]
