# Generated by Django 6.0.6 on 2026-09-07 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_alter_color_color'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Color',
        ),
    ]
