# Generated by Django 6.0.6 on 2026-09-19 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_delete_color'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='company_name',
            new_name='last_name',
        ),
    ]
