# Generated by Django 6.0.6 on 2026-09-20 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_rename_company_name_order_last_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_logo', models.ImageField(blank=True, null=True, upload_to='site_settings/')),
                ('admin_logo', models.ImageField(blank=True, null=True, upload_to='site_settings/')),
                ('banner', models.ImageField(blank=True, null=True, upload_to='site_settings/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
