# Generated by Django 6.0.6 on 2026-09-20 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_sitesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='sidebar_logo',
            field=models.ImageField(blank=True, null=True, upload_to='site_settings/'),
        ),
    ]
