# Generated by Django 6.0.6 on 2026-09-20 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_sitesettings_sidebar_logo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sitesettings',
            old_name='banner',
            new_name='banner_1',
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='banner_2',
            field=models.ImageField(blank=True, null=True, upload_to='site_settings/'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='banner_3',
            field=models.ImageField(blank=True, null=True, upload_to='site_settings/'),
        ),
    ]
